- name: SSM showcase
  hosts: all
  vars:
    file: 100mb_file.bin
  tasks:
    - name: Copy the file normally
      ansible.builtin.copy:
        src: "files/{{ file }}"
        dest: "{{ file }}"
        mode: '640'
    - name: Cleanup
      ansible.builtin.file:
        path: "{{ file }}"
        state: absent
